# Generated by Django 3.1.3 on 2020-12-01 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201130_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phoneno',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, unique=True, verbose_name='contact number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
